backend:
  name: github
  repo: viradh-07/goodnews
  branch: main
  base_url: https://goodnews-xb65-git-main-viradh07-hubs-projects.vercel.app

media_folder: "images"
public_folder: "images"

collections:
  - name: "content_repository"
    label: "Content Repository"
    label_singular: "News Article"
    folder: "content/posts" 
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    summary: "{{headline}}"
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["entertainment", "lifestyle", "sports", "international", "offbeat", "business", "tech-ai"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Content Body", name: "body", widget: "markdown" }
