backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "content_repository"
    label: "Content Repository"
    label_singular: "News Article"
    folder: "content/posts" 
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    summary: "{{headline}}"
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Content Body", name: "body", widget: "text" }
